updatesPullRequest
valreron/HillelValerMokryn pull request #13
Opened 2023-01-04 21:01 UTC by valreron

2023-01-05 08:42 UTC, apollyonix requested changes
Можна позбутися класу Utils і розкидати його методи по існуючим класам
Також треба замінити генерацію ексепшена на асерт в тестах

2023-01-05 08:42 UTC, apollyonix commented on src/test/java/lessons/homeworkOfLesson18/ClickTest.java
> +        utils.loginIn(driver, userName, "tomsmith", userPass, "SuperSecretPassword!");
а в чому смисл винести частину коду для логіну (щоб не дублювати його), але в кожному тесті шукати одні і ті ж самі елементи, щоб потім в цей метод передати?))

2023-01-05 08:42 UTC, apollyonix commented on src/test/java/lessons/homeworkOfLesson18/Utils.java
> +    public void openSuite(WebDriver driver, String url) {
такий метод можна закинути в базовий тест

2023-01-05 08:42 UTC, apollyonix commented on src/test/java/lessons/homeworkOfLesson18/Utils.java
> +    public void loginIn(WebDriver driver, WebElement userName, String inputName, WebElement userPass, String inputPass) {  //true pass, zero login
чисто теоретично - в реальних тестах логін потрібен кожному з них, тому можна також закинути в базовий.
в цьому ж випадку - це допоміжний метод тільки для одного тесту (групи тестів), тому краще було тримати його в тому ж класі. в такому випадку не потрібно буде постійно переключатися між класами

2023-01-05 08:42 UTC, apollyonix commented on src/test/java/lessons/homeworkOfLesson18/Utils.java
> +            throw new ButtonNotFoundException();
трохи некоректна логіка. порівнюємо текст зі сторінки з очцкуваним. якщо не співпадає - то кидаємо ексепшн, що не знайшли кнопку.
тут можна використати простий assert

2023-01-05 18:38 UTC, valreron commented on src/test/java/lessons/homeworkOfLesson18/ClickTest.java
> +        utils.loginIn(driver, userName, "tomsmith", userPass, "SuperSecretPassword!");
виніс під "предлогом", що мб десь в інших тестах поле логіну і паролю будуть під іншим ідентифікатором

2023-01-05 19:23 UTC, valreron reviewed
changes

2023-01-06 08:28 UTC, apollyonix approved these changes

2023-01-06 08:28 UTC, merged